### ISSUE TITLE
Migrate documentation from readthedocs to vcpkg website

### ISSUE THREAD

**Issue by AugP** [vcpkg/vcpkg.github.io#12]
Move the vcpkg documentation to the main website. 

Tasks: 

- [x] Create a view with a Table of Contents that can serve as a container for the documentation
- [x] Copy over the existing docs to the new location
- [x] Replace the links on the website and vcpkg GitHub repo with link to new docs

**Comment by autoantwort** [comment]
Maybe more important: Keep the documentation up to date! This site is quite useless if the documentation is always outdated and you have to look thinks up in the vcpkg repo anyways.  
So maybe simply add a cron job that syncs the documentation from the vcpkg repo every day. Similar to #21

**Comment by AugP** [comment]
> Maybe more important: Keep the documentation up to date! This site is quite useless if the documentation is always outdated and you have to look thinks up in the vcpkg repo anyways.
> So maybe simply add a cron job that syncs the documentation from the vcpkg repo every day. Similar to #21

I agree, this is something the team was thinking about as well. I created a new issue based on your suggestion. I think we can close this one since its original purpose has been fulfilled, but we can continue the discussion over some kind of auto-sync mechanic in the new issue.
