### ISSUE TITLE
[docs] search prompt box doesn’t minimize

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#23]
- [ ] https://vcpkg.io/en/docs/users/versioning.html

Repro: 
1.	Click the ‘search’ box in maxmize window
2.	Minimize the window
3.	You can see the prompt box doesn’t minimize

Expect: The prompt box minimize.

![image](https://user-images.githubusercontent.com/20694052/116235211-2999b300-a790-11eb-9d52-a8ef2852bde4.png)

**Comment by dan-shaw** [comment]
Fixed in a8ddb5af5d7057ac71e09317ec81c8f25c9395c9
