### ISSUE TITLE
[packages] Should not display 'Build-Depends:' if the feature doesn't have any dependents.

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#25]
- [ ] https://vcpkg.io/en/packages.html

The feature doesn't have any depends, so it should not display 'Build-Depends:'. see https://github.com/microsoft/vcpkg/blob/master/ports/ace/CONTROL

![image](https://user-images.githubusercontent.com/20694052/116235868-ef7ce100-a790-11eb-9e15-ad2d71532174.png)

**Comment by dan-shaw** [comment]
Fixed in a8ddb5af5d7057ac71e09317ec81c8f25c9395c9
