### ISSUE TITLE
[docs] The provided links are broken

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#26]
List:
- [x] [CONTROL files](https://vcpkg.io/en/docs/maintainers/control-files.html) the links in for 'vcpkg.json'.

**Comment by NancyLi1013** [comment]
- [ ] [Config Environment](https://vcpkg.io/en/docs/users/config-environment.html) the links in `VCPKG_DEFAULT_HOST_TRIPLET ` item for 'the Tools documentation' 
 - [ ] [Config Environment](https://vcpkg.io/en/docs/users/config-environment.html) the links in `VCPKG_OVERLAY_PORTS` item for 'ports overlay' 
 - [ ] [Config Environment](https://vcpkg.io/en/docs/users/config-environment.html) the links in `VCPKG_OVERLAY_TRIPLETS` item for ' Example: overlay triplets'

**Comment by NancyLi1013** [comment]
- [ ] In **users/android** page https://vcpkg.io/en/docs/users/android.html, these links are all broken.
 `docs/examples/vcpkg_android_example_cmake` in **[Test on an example](https://vcpkg.io/en/docs/users/android.html#test-on-an-example)** item
 `CMakeLists` in **[Test on an example](https://vcpkg.io/en/docs/users/android.html#test-on-an-example)** item
`my_lib.cpp` in **[Test on an example](https://vcpkg.io/en/docs/users/android.html#test-on-an-example)** item
`vcpkg_android.cmake` in [Test on an example, using vcpkg_android.cmake ](https://vcpkg.io/en/docs/users/android.html#test-on-an-example-using-vcpkg_androidcmakeexamplesvcpkg_android_example_cmake_scriptcmakevcpkg_androidcmake) item
`docs/examples/vcpkg_android_example_cmake_script` in [Test on an example, using vcpkg_android.cmake ](https://vcpkg.io/en/docs/users/android.html#test-on-an-example-using-vcpkg_androidcmakeexamplesvcpkg_android_example_cmake_scriptcmakevcpkg_androidcmake) item
`CMakeLists` in [Test on an example, using vcpkg_android.cmake ](https://vcpkg.io/en/docs/users/android.html#test-on-an-example-using-vcpkg_androidcmakeexamplesvcpkg_android_example_cmake_scriptcmakevcpkg_androidcmake) item
`vcpkg_android.cmake` [Test on an example, using vcpkg_android.cmake ](https://vcpkg.io/en/docs/users/android.html#test-on-an-example-using-vcpkg_androidcmakeexamplesvcpkg_android_example_cmake_scriptcmakevcpkg_androidcmake) item
`compile.sh` in [Test on an example, using vcpkg_android.cmake ](https://vcpkg.io/en/docs/users/android.html#test-on-an-example-using-vcpkg_androidcmakeexamplesvcpkg_android_example_cmake_scriptcmakevcpkg_androidcmake) item

**Comment by NancyLi1013** [comment]
- [ ] Feature Packages in **[Further reading](https://vcpkg.io/en/docs/users/selecting-library-features.html)**
