### ISSUE TITLE
[docs] Garbled character

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#27]
- [ ] https://vcpkg.io/en/docs/users/versioning.reference.html#builtin-baseline

users->versioning.reference->Version constraints ->builtin-baseline

![image](https://user-images.githubusercontent.com/20694052/116343196-935ca000-a816-11eb-92df-0eb120125cee.png)

The original docs: [users/versioning.reference.md](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.reference.md) is correct.
If there’s no local baseline file, vcpkg will use the version currently available in the ports directory.
Baselines can be used without any other version constraints to obtain behavior close to using “classic” mode.

**Comment by Cheney-W** [comment]
https://vcpkg.io/en/docs/examples/patching.html#initial-error-logs

example->patching->Initial error logs
![image](https://user-images.githubusercontent.com/38240633/116354780-7e3e3c00-a82b-11eb-81ca-8fc62f2cc6ca.png)

**Comment by Cheney-W** [comment]
https://vcpkg.io/en/docs/users/versioning.implementation-details.html

user->Versioning: Implementation details->Constraint resolution
![image](https://user-images.githubusercontent.com/38240633/116361300-679be300-a833-11eb-823a-d2d647d90f6f.png)

**Comment by Cheney-W** [comment]
https://vcpkg.io/en/docs/users/versioning.implementation-details.html#constraint-resolution
user->Versioning: Implementation details->Acquiring port versions
![image](https://user-images.githubusercontent.com/38240633/116361648-c6f9f300-a833-11eb-934d-3a6bbb15d3c5.png)

**Comment by Cheney-W** [comment]
https://vcpkg.io/en/docs/users/versioning.reference.html
users->versioning.reference->Version schemes
![image](https://user-images.githubusercontent.com/38240633/116362224-6a4b0800-a834-11eb-8652-e11c09bb021b.png)
