### ISSUE TITLE
[doc] Link name error

### ISSUE THREAD

**Issue by Cheney-W** [vcpkg/vcpkg.github.io#31]
https://vcpkg.io/en/docs/README.html

README->Examples
Following item should named as: Patching Example: Patching libpng to work for **x64-uwp**
![image](https://user-images.githubusercontent.com/38240633/116364484-d169bc00-a836-11eb-8e47-b9a0fe87ca9b.png)

**Comment by PhoebeHui** [comment]
- [ ] https://vcpkg.io/en/docs/users/config-environment.html 

users ->config-environment ->Environment and Configuration->VCPKG_VISUAL_STUDIO_PATH 

![image](https://user-images.githubusercontent.com/20694052/116375035-77222880-a841-11eb-9117-721efe8b0dcc.png)
