### ISSUE TITLE
[docs] The font sizes are inconsistent

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#33]
- [ ] https://vcpkg.io/en/docs/maintainers/manifest-files.html

maintainers ->Manifest files 

![image](https://user-images.githubusercontent.com/20694052/116365120-869c7400-a837-11eb-9d61-14defcfe4ed3.png)

**Comment by PhoebeHui** [comment]
https://vcpkg.io/en/docs/examples/overlay-triplets-linux-dynamic.html

Overlay triplets example -> Building dynamic libraries on Linux ->Step 2: 

![image](https://user-images.githubusercontent.com/20694052/116366058-78028c80-a838-11eb-8ce7-d94e8628f2b5.png)

**Comment by PhoebeHui** [comment]
- [ ]  https://vcpkg.io/en/docs/examples/packaging-zipfiles.html

examples ->Packaging Zipfiles -> Packaging Zipfiles Example: zlib ->Bootstrap with create
![image](https://user-images.githubusercontent.com/20694052/116368444-e9dbd580-a83a-11eb-90fb-85d1e78fcad0.png)

**Comment by PhoebeHui** [comment]
- [ ] https://vcpkg.io/en/docs/users/binarycaching.html#valid-source-strings-source

users->binarycaching.html->valid-source-strings-source

![image](https://user-images.githubusercontent.com/20694052/116374049-86ed3d00-a840-11eb-8b9a-fdf96d28fb89.png)

**Comment by PhoebeHui** [comment]
- [ ] https://vcpkg.io/en/docs/users/manifests.html#name-field

Similar issue in this page

**Comment by dan-shaw** [comment]
Fixed in a8ddb5af5d7057ac71e09317ec81c8f25c9395c9
