### ISSUE TITLE
[packages] The contents are null in Feature List

### ISSUE THREAD

**Issue by NancyLi1013** [vcpkg/vcpkg.github.io#34]
In [Browse packages](https://vcpkg.io/en/packages.html), when picking `Feature List` item for some packages, there is no any content. Such as `abseil`:

![Capture](https://user-images.githubusercontent.com/46708020/116372722-4b05a800-a83f-11eb-940d-cfdb235789cc.PNG)

**Comment by NancyLi1013** [comment]
Seems this is related with the format of file. Such as if it is manifest(vcpkg.json), the feature cannot be listed.

`sqlie3`, `sqitecpp` packages have the same problem.

**Comment by dan-shaw** [comment]
Fixed in a8ddb5af5d7057ac71e09317ec81c8f25c9395c9
