### ISSUE TITLE
[docs] The files in sub folders didn't generate correctly

### ISSUE THREAD

**Issue by PhoebeHui** [vcpkg/vcpkg.github.io#39]
In original docs https://github.com/microsoft/vcpkg/tree/master/docs/examples/vcpkg_android_example_cmake

In website:
![image](https://user-images.githubusercontent.com/20694052/116500248-b6538680-a8e0-11eb-84d9-b5db2c183c56.png)

Related to https://github.com/vcpkg/vcpkg.github.io/issues/26#issuecomment-828329954

**Comment by dan-shaw** [comment]
This is by design; the example does not have markdown documentation.
