### ISSUE TITLE
SQL error: no such function: json

### ISSUE THREAD

**Issue by Manfred-O** [vcpkg/vcpkg.github.io#63]
Hi, 
i am not sure how to setup the sqlite3 json1 extension correctly in visual studio, but i have them. 

C:\Projekte\vcpkg>vcpkg.exe list
json-c:x64-windows                                 2019-09-10#1     A JSON implementation in C
json-c:x64-windows-static                          2019-09-10#1     A JSON implementation in C
json-c:x86-windows                                 2019-09-10#1     A JSON implementation in C
json-c:x86-windows-static                          2019-09-10#1     A JSON implementation in C
sqlite3:x64-windows                                3.35.4#1         SQLite is a software library that implements a s...
sqlite3:x64-windows-static                         3.35.4#1         SQLite is a software library that implements a s...
sqlite3:x86-windows                                3.35.4#1         SQLite is a software library that implements a s...
sqlite3[json1]:x64-windows-static                                   enable JSON functionality for sqlite3

Now when coding i allways get described error. 

    char* err_msg = 0;
    sqlite3* db;

    int rc = sqlite3_open_v2(
        "test.db",
        &db,
        SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE,
        NULL
    );

    if (rc != SQLITE_OK) {
        fprintf(stderr, "Cannot open database: %s\n", sqlite3_errmsg(db));
        sqlite3_free(err_msg);
        sqlite3_close(db);
        return 0;
    }

    if (sqlite3_exec(db, "create table user(name, phone);", printDB, NULL, &err_msg) != SQLITE_OK) {
        fprintf(stderr, "SQL error: %s\n", err_msg);
    }

    if (sqlite3_exec(db, "insert into user (name, phone) values(\"oz\", json('{\"cell\":\"+491765\", \"home\":\"+498973\"}'));", printDB, NULL, &err_msg) != SQLITE_OK) {
        fprintf(stderr, "SQL error: %s\n", err_msg);  **<< this line causes my error???????**
    }

    if (sqlite3_exec(db, "select user.phone from user where user.name=='oz';", printDB, NULL, &err_msg) != SQLITE_OK) {
        fprintf(stderr, "SQL error: %s\n", err_msg);
    }

Greetings

**Comment by vicroms** [comment]
Please [create an issue in the Microsoft/vcpkg repository](https://github.com/microsoft/vcpkg/issues/new/choose). 
Only create issues related to the website in this repository.
