### ISSUE TITLE
Unable to install VCPKG

### ISSUE THREAD

**Issue by chai1301** [vcpkg/vcpkg.github.io#77]
I downloaded the vcpkg repo from git. Hitting the below error when ./bootstrap-vcpkg.bat is run:

_*C:\vcpkg-master\scripts\bootstrap.ps1 : Downloading vcpkg.exe failed. Please check your internet connection, or
consider downloading a recent vcpkg.exe from https://github.com/microsoft/vcpkg-tool with a browser.**
At line:1 char:4*
+ & {& 'C:\vcpkg-master\scripts\bootstrap.ps1' }
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1
ScriptHalted
At C:\vcpkg-master\scripts\bootstrap.ps1:60 char:5
    + CategoryInfo          : OperationStopped: (:) [], RuntimeException
    + FullyQualifiedErrorId : ScriptHalted_

I tried installing it from the vcpkg-tool as well. In there, there aren't any executables named as vcpkg.
Kindly help to install vcpkg.

**Comment by vicroms** [comment]
Please [create an issue in the Microsoft/vcpkg repository](https://github.com/microsoft/vcpkg/issues/new/choose). 
Only create issues related to the website in this repository.
