### ISSUE TITLE
can not found the ffmpeg in vcpkg.io website

### ISSUE THREAD

**Issue by xiaoyifang** [vcpkg/vcpkg.github.io#85]
[**Describe the bug**
https://vcpkg.io/en/packages.html

can not found the ffmpeg package.
and the display result is wrong.

![image](https://user-images.githubusercontent.com/105986/195235106-70dc80da-bb08-46f5-890c-926e949f78dd.png)

**Comment by PhoebeHui** [comment]
@xiaoyifang, thanks for reportingt this issue! Looks this issue had been fixed. See

![image](https://user-images.githubusercontent.com/20694052/228750098-b2a7b23a-edc0-4970-8a4d-41c4f02a601c.png)
