### ISSUE TITLE
California Privacy Choice overlaps at low screen resolution

### ISSUE THREAD

**Issue by terrimorton** [vcpkg/vcpkg.github.io#97]
**URL example**: https://vcpkg.io/en/index.html

**Repro**:

- Chrome
- Using Developer Tools, set the Dimentions to Responsive, width 360
- Note that the Your Californation Privacy Choices overlaps text in the 3rd column

**Screenshot**:
![Snag_66e614d0](https://user-images.githubusercontent.com/4643903/218507110-82b4f56b-cc18-48ee-9593-7421f3741845.png)

**Comment by Sreenivas-Kalluru** [comment]
Hi @terrimorton ,

The responsiveness fix changes are deployed to production, the below snapshot is the latest one.
![image](https://user-images.githubusercontent.com/69580789/220071905-6f956236-62cf-4b15-8aa5-5d255c036c2a.png)

Could you please verify and let me know if any issues.

**Comment by terrimorton** [comment]
This now looks reasonable at 360.

![image](https://user-images.githubusercontent.com/4643903/220419199-8d591e04-3a8e-45e4-b5b0-4a525a11030a.png)
